// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQK5DM2HnaEm63cJu2Z803M7EEnGQH2rw',
    appId: '1:307211949059:web:22fc5fbb9545645d842a36',
    messagingSenderId: '307211949059',
    projectId: 'flutterom-lab-firebasr',
    authDomain: 'flutterom-lab-firebasr.firebaseapp.com',
    storageBucket: 'flutterom-lab-firebasr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpdBqm-Qrwo7SuQ8kT2XpP6jmvjpqoCjg',
    appId: '1:307211949059:android:4ca4b71dbb2c1936842a36',
    messagingSenderId: '307211949059',
    projectId: 'flutterom-lab-firebasr',
    storageBucket: 'flutterom-lab-firebasr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCDXCqojIW-tnNrp5Y2zMdOneaygX4ZO0',
    appId: '1:307211949059:ios:0cc4c3d8f4af9671842a36',
    messagingSenderId: '307211949059',
    projectId: 'flutterom-lab-firebasr',
    storageBucket: 'flutterom-lab-firebasr.appspot.com',
    iosClientId: '307211949059-1e7mhud2lq8gic5juv2am6fk9neo3jij.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCDXCqojIW-tnNrp5Y2zMdOneaygX4ZO0',
    appId: '1:307211949059:ios:0cc4c3d8f4af9671842a36',
    messagingSenderId: '307211949059',
    projectId: 'flutterom-lab-firebasr',
    storageBucket: 'flutterom-lab-firebasr.appspot.com',
    iosClientId: '307211949059-1e7mhud2lq8gic5juv2am6fk9neo3jij.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthen',
  );
}